changelog:
  categories:
    - title: Breaking Changes
      labels:
        - major
    - title: New Features
      labels:
        - minor
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - documentation
    - title: Other Changes
      labels:
        - "*"
